# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the version that matches your environment
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the version that matches your environment
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the version that matches your environment
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the version that matches your environment
    hooks:
      - id: flake8
        args: [--max-line-length=120]
