version: '3.1'

services:

  tdd-db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tdd-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
