# Generated by Django 4.2.5 on 2023-10-07 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the list", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PENDING",
                        help_text="Status of the list",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns the list",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the item", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PENDING",
                        help_text="Status of the item",
                        max_length=10,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="List to which the item belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="todo.list",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
