# Generated by Django 4.2.5 on 2023-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="content",
            field=models.TextField(default="", help_text="Content of the item"),
            preserve_default=False,
        ),
    ]
